# Generated by Django 3.2.18 on 2023-03-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDBFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255)),
                ('flat_type', models.CharField(max_length=255)),
                ('flat_model', models.CharField(max_length=255)),
                ('floor_area_sqm', models.DecimalField(decimal_places=0, max_digits=15)),
                ('street_name', models.CharField(max_length=255)),
                ('resale_price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('month', models.CharField(max_length=255)),
                ('remaining_lease', models.CharField(max_length=255)),
                ('lease_commence_date', models.CharField(max_length=255)),
                ('storey_range', models.CharField(max_length=255)),
                ('id_str', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
